# Generated by Django 5.0.4 on 2024-07-22 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodapp.basemodel')),
                ('category_name', models.CharField(max_length=50)),
            ],
            bases=('foodapp.basemodel',),
        ),
        migrations.CreateModel(
            name='FoodComment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodapp.basemodel')),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='foodapp.foodcomment')),
            ],
            bases=('foodapp.basemodel',),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodapp.basemodel')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='foodapp.foodcomment')),
            ],
            bases=('foodapp.basemodel',),
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodapp.basemodel')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image/recipe/')),
                ('cook_time', models.IntegerField()),
                ('serves', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('category', models.ManyToManyField(to='foodapp.category', verbose_name='Categories')),
                ('views_number', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='ViewsNumber')),
            ],
            bases=('foodapp.basemodel',),
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodapp.basemodel')),
                ('text', models.TextField()),
                ('image_1', models.ImageField(upload_to='media/instructions/')),
                ('image_2', models.ImageField(upload_to='media/instructions/')),
                ('image_3', models.ImageField(upload_to='media/instructions/')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.recipes')),
            ],
            bases=('foodapp.basemodel',),
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodapp.basemodel')),
                ('text', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.recipes')),
            ],
            bases=('foodapp.basemodel',),
        ),
        migrations.CreateModel(
            name='FoodLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_likes', to='foodapp.recipes')),
            ],
        ),
        migrations.AddField(
            model_name='foodcomment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='foodapp.recipes'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('author', 'comment'), name='CommentLikeUnique'),
        ),
        migrations.AddConstraint(
            model_name='foodlike',
            constraint=models.UniqueConstraint(fields=('author', 'recipe'), name='postLikeUnique'),
        ),
    ]
