# Generated by Django 5.0.4 on 2024-07-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodapp.basemodel')),
                ('category_name', models.CharField(max_length=50)),
            ],
            bases=('foodapp.basemodel',),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodapp.basemodel')),
            ],
            bases=('foodapp.basemodel',),
        ),
        migrations.CreateModel(
            name='FoodComment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodapp.basemodel')),
                ('comment', models.TextField()),
            ],
            bases=('foodapp.basemodel',),
        ),
        migrations.CreateModel(
            name='FoodLike',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodapp.basemodel')),
            ],
            bases=('foodapp.basemodel',),
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodapp.basemodel')),
                ('text', models.TextField()),
            ],
            bases=('foodapp.basemodel',),
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodapp.basemodel')),
                ('text', models.TextField()),
                ('image_1', models.ImageField(upload_to='media/instructions/')),
                ('image_2', models.ImageField(upload_to='media/instructions/')),
                ('image_3', models.ImageField(upload_to='media/instructions/')),
            ],
            bases=('foodapp.basemodel',),
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodapp.basemodel')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image/recipe/')),
                ('cook_time', models.IntegerField()),
                ('serves', models.IntegerField()),
                ('views_number', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
            ],
            bases=('foodapp.basemodel',),
        ),
        migrations.CreateModel(
            name='SaveModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodapp.basemodel')),
            ],
            bases=('foodapp.basemodel',),
        ),
    ]
