# Generated by Django 5.0.4 on 2024-07-25 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_alter_recipes_views_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructions',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='instructions',
            name='recipe',
        ),
        migrations.RemoveConstraint(
            model_name='foodlike',
            name='postLikeUnique',
        ),
        migrations.AddConstraint(
            model_name='foodlike',
            constraint=models.UniqueConstraint(fields=('author', 'recipe'), name='foodLikeUnique'),
        ),
        migrations.DeleteModel(
            name='Instructions',
        ),
    ]
