# Generated by Django 5.0.4 on 2024-07-23 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_alter_recipes_views_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodapp.basemodel')),
            ],
            bases=('foodapp.basemodel',),
        ),
        migrations.RemoveConstraint(
            model_name='foodlike',
            name='postLikeUnique',
        ),
        migrations.AddConstraint(
            model_name='foodlike',
            constraint=models.UniqueConstraint(fields=('author', 'recipe'), name='foodLikeUnique'),
        ),
        migrations.AddField(
            model_name='savemodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savemodel',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save', to='foodapp.foodcomment'),
        ),
        migrations.AddConstraint(
            model_name='savemodel',
            constraint=models.UniqueConstraint(fields=('author', 'recipe'), name='SaveUnique'),
        ),
    ]
