# Generated by Django 5.0.4 on 2024-07-23 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_savemodel_remove_foodlike_postlikeunique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savemodel',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save', to='foodapp.recipes'),
        ),
    ]
