# Generated by Django 5.0.4 on 2024-07-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodapp', '0003_remove_instructions_basemodel_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='instructionsapp.basemodel')),
                ('text', models.TextField()),
                ('image_1', models.ImageField(upload_to='media/instructions/')),
                ('image_2', models.ImageField(upload_to='media/instructions/')),
                ('image_3', models.ImageField(upload_to='media/instructions/')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.recipes')),
            ],
            bases=('instructionsapp.basemodel',),
        ),
    ]
