# Generated by Django 5.0.4 on 2024-04-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconfirmation',
            options={'ordering': ['-created_at']},
        ),
    ]
