# Generated by Django 5.0.4 on 2024-07-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_users_followers_alter_users_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietarymodel',
            name='name_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='dietarymodel',
            name='name_uz',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
