# Generated by Django 5.0.4 on 2024-04-29 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='owner',
        ),
        migrations.AddField(
            model_name='recipes',
            name='recipe_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='views_number',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='ViewsNumber'),
        ),
    ]
